Tools to consider in your toolbox:

  * Easy data import from structured text​

  * Easily organize 2d data by column/row​

  * Merge in other data​

  * Make new variables​

  * Modify existing variables​

  * Apply functions across different dimensions​

  * Apply a function by group​

  * Visualize all results
  
The missing link. ​

For effective Data science/analytics, we need something at least as good as excel.​

The scripting in Python is good till now, but what about data organization or handling columns of tabular data with different types? ​

Pandas focuses on data management which can be combined with analytics tools​

Pandas is built on top of NumPy, making it very fast

“High level data structures”​

  * Labeled axes
  
  * Easy indexing/sorting
  
  * Easy maintenance​

  * Vectorization​

  * Applying functions across different aspects of the data​

  * Missing data recognition​

  * SQL style merging ​

  * Easy Reshaping, with functions applied on the reshape​
  
This is the central object we will consider in Pandas​

  - Others are the Series and the Panel​

You can think of it like an Excel spreadsheet or (more appropriately) like a database table​

  - Tabular​

  - Same dtype within Column, dtype can vary by column​
  
<div style="font-size:18px">Create Data Frame</div>

We can create a dataframe by passing in a dict of equal length lists​

  * Dict keys will be column names​

We can also create dataframes from file loads and queries

In [21]:
# Make Dataframe
import pandas as pd 
import numpy as np
np.random.seed(123)
data = {'custid': list(range(1,11)),
'year': list(range(2010,2015))*2,
'spent': np.random.randint(10,50,10)}
frame = pd.DataFrame(data)
frame

   custid  year  spent
0       1  2010     12
1       2  2011     38
2       3  2012     44
3       4  2013     48
4       5  2014     27
5       6  2010     29
6       7  2011     32
7       8  2012     43
8       9  2013     42
9      10  2014     19

Pandas provides a lot of functionality for manipulating data​

  * Transposing rows and columns​

  * Shaping data​

  * Data labeling​

  * NumPy conversion​

  * Getting heads/tails of datasets​

  * Importing/exporting​

  * Statistical functions such as sum, mean, std, median, etc.​
  
<div style="font-size:18px">Index</div>

Axis Values are “Indexes” (not like a database index)​

Indexes allow us to easily subset rows and columns, similar to indexing lists and tuples​

In [17]:
# Assign Index
frame = pd.DataFrame(data,
                     index=["one","two","three","four","five",
                            "six","seven","eight","nine","ten"])

# Alternatively
frame.index=["one","two","three","four","five",
             "six","seven","eight","nine","ten"]

frame

       custid  year  spent
one         1  2010     12
two         2  2011     38
three       3  2012     44
four        4  2013     48
five        5  2014     27
six         6  2010     29
seven       7  2011     32
eight       8  2012     43
nine        9  2013     42
ten        10  2014     19

<div style="font-size:18px">Series</div> 

1-Dimensional Pandas Object, similar to DF​

We will not focus on Series data, but you may use it​

Created with **Series()** command ​

Elements can be named (indexed)​

In [13]:
# Series - 1-d Object with Labels (Indexes)
s1 = pd.Series({'custid': list(range(1,6))*2})
s1
s2 = pd.Series({'day1': 45, 'day2': 55, 'day3': 27})
s2

custid    [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
dtype: object

<div style="font-size:18px">Change Dataframe Columns</div> 

Simply assign a list of the new column names to the dataframe

In [25]:
# Change Columns
frame
frame.columns = ["custid","date","mon_spent"]
frame

   custid  date  mon_spent
0       1  2010         12
1       2  2011         38
2       3  2012         44
3       4  2013         48
4       5  2014         27
5       6  2010         29
6       7  2011         32
7       8  2012         43
8       9  2013         42
9      10  2014         19

<div style="font-size:18px">Importing Structured Text</div>

Probably the most common operation is to import CSV to pandas DF for further analysis. ​

If you have multiple tables/data sources, you import multiple CSVs.​

You can also import HDF5, excel, JSON, and the clipboard. ​

http://pandas.pydata.org/pandas-docs/stable/io.html​

In [86]:
# Import Dataframe
%cd
import os
xy="." + os.sep + "NIH_Python_Tutorial" + os.sep + "Jupyter Python Class" + os.sep + "Datasets" + os.sep + "states.csv"
states = pd.read_csv(xy)

C:\Users\jrcha
Index(['State', 'Population', 'Income', 'Illiteracy', 'Life Exp', 'Murder',
       'HS Grad', 'Frost', 'Area'],
      dtype='object')

As soon as we import data, step one should be to check the data import​

Are the number of rows as expected? What about the column names? General range of continuous variables? ​

In [88]:
# View
states.head(n=5)
states.tail(n=5)
states.describe()
 
# Number of Rows
len(states)

50

<div style="font-size:18px">Rows and Columns</div> 

We also may want to look at just the list of row identifiers, or column identifiers. These are stored as attributes.

These “index” objects have a .values attribute if we want just a list, instead of an “index” object. ​

In [94]:
# List Columns
states.columns
states.columns.values
 
#states['State':'Income'] # doesn't work

# List row IDs
#states.index

array(['State', 'Population', 'Income', 'Illiteracy', 'Life Exp',
       'Murder', 'HS Grad', 'Frost', 'Area'], dtype=object)

<div style="font-size:18px">Indexes</div> 

The word index should be generalized to rows and columns conceptually​

But, the author of the package uses index to imply rows at times. We can select by indexes (rows and columns) in a variety of ways, some of which seem inconsistent. ​

In [118]:
# Indexing
# Select Column
states['State']
states[['Area', 'State']]
 
# By column name attribute
states.State

0            Alabama
1             Alaska
2            Arizona
3           Arkansas
4         California
5           Colorado
6        Connecticut
7           Delaware
8            Florida
9            Georgia
10            Hawaii
11             Idaho
12          Illinois
13           Indiana
14              Iowa
15            Kansas
16          Kentucky
17         Louisiana
18             Maine
19          Maryland
20     Massachusetts
21          Michigan
22         Minnesota
23       Mississippi
24          Missouri
25           Montana
26          Nebraska
27            Nevada
28     New Hampshire
29        New Jersey
30        New Mexico
31          New York
32    North Carolina
33      North Dakota
34              Ohio
35          Oklahoma
36            Oregon
37      Pennsylvania
38      Rhode Island
39    South Carolina
40      South Dakota
41         Tennessee
42             Texas
43              Utah
44           Vermont
45          Virginia
46        Washington
47     West Virginia
48         Wisconsin
49           Wyoming
Name: State, dtype: object

We can index with integers, which imply row indexing.​

We can also index with boolean 1d​

Or a full 2-d boolean the same size (nonsensical in this example)​

In [126]:
# Select Row (labels, index)
#states[0:2]
 
# select by boolean row
states[states.Murder < 10]
 
# select by boolean array
#states[states < 1000]

,State,Population,Income,Illiteracy,Life Exp,Murder,HS Grad,Frost,Area
2,Arizona,2212,4530,1.8,70.55,7.8,58.1,15,113417
5,Colorado,2541,4884,0.7,72.06,6.8,63.9,166,103766
6,Connecticut,3100,5348,1.1,72.48,3.1,56.0,139,4862
7,Delaware,579,4809,0.9,70.06,6.2,54.6,103,1982
10,Hawaii,868,4963,1.9,73.60,6.2,61.9,0,6425
11,Idaho,813,4119,0.6,71.87,5.3,59.5,126,82677
13,Indiana,5313,4458,0.7,70.88,7.1,52.9,122,36097
14,Iowa,2861,4628,0.5,72.56,2.3,59.0,140,55941
15,Kansas,2280,4669,0.6,72.58,4.5,59.9,114,81787
18,Maine,1058,3694,0.7,70.39,2.7,54.7,161,30920
19,Maryland,4122,5299,0.9,70.22,8.5,52.3,101,9891
20,Massachusetts,5814,4755,1.1,71.83,3.3,58.5,103,7826
22,Minnesota,3921,4675,0.6,72.96,2.3,57.6,160,79289
24,Missouri,4767,4254,0.8,70.69,9.3,48.8,108,68995
25,Montana,746,4347,0.6,70.56,5.0,59.2,155,145587
26,Nebraska,1544,4508,0.6,72.60,2.9,59.3,139,76483
28,New Hampshire,812,4281,0.7,71.23,3.3,57.6,174,9027
29,New Jersey,7333,5237,1.1,70.93,5.2,52.5,115,7521
30,New Mexico,1144,3601,2.2,70.32,9.7,55.2,120,121412
33,North Dakota,637,5087,0.8,72.78,1.4,50.3,186,69273
34,Ohio,10735,4561,0.8,70.82,7.4,53.2,124,40975
35,Oklahoma,2715,3983,1.1,71.42,6.4,51.6,82,68782
36,Oregon,2284,4660,0.6,72.13,4.2,60.0,44,96184
37,Pennsylvania,11860,4449,1.0,70.43,6.1,50.2,126,44966
38,Rhode Island,931,4558,1.3,71.90,2.4,46.4,127,1049
40,South Dakota,681,4167,0.5,72.08,1.7,53.3,172,75955
43,Utah,1203,4022,0.6,72.90,4.5,67.3,137,82096
44,Vermont,472,3907,0.6,71.64,5.5,57.1,168,9267
45,Virginia,4981,4701,1.4,70.08,9.5,47.8,85,39780
46,Washington,3559,4864,0.6,71.72,4.3,63.5,32,66570
47,West Virginia,1799,3617,1.4,69.48,6.7,41.6,100,24070
48,Wisconsin,4589,4468,0.7,72.48,3.0,54.5,149,54464
49,Wyoming,376,4566,0.6,70.29,6.9,62.9,173,97203

Pandas Provides three methods for indexing​

**.iloc()**   index by integer location, similar to numpy​

**.loc()**    index by label location (end inclusive)​

**.ix()**      index by either integer or label (deprecated)​

In [131]:
from biopandas.pdb import PandasPdb
ppdb = PandasPdb().fetch_pdb('3eiy')
ppdb.df['ATOM'].head()

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
0,ATOM,1,,N,,SER,,A,2,,...,2.527,54.656,-1.667,1.0,52.73,,,N,NaN,611
1,ATOM,2,,CA,,SER,,A,2,,...,3.259,54.783,-0.368,1.0,52.54,,,C,NaN,612
2,ATOM,3,,C,,SER,,A,2,,...,4.127,53.553,-0.105,1.0,52.03,,,C,NaN,613
3,ATOM,4,,O,,SER,,A,2,,...,5.274,53.451,-0.594,1.0,52.45,,,O,NaN,614
4,ATOM,5,,CB,,SER,,A,2,,...,2.273,54.944,0.792,1.0,52.69,,,C,NaN,615

FileNotFoundError: [Errno 2] No such file or directory: './docking_pose_1.pdb'

In [ ]:
# select by integer location
states.iloc[0:3,0:4] #not end inclusive
 
# select by label only
states.loc[0:15,"Population":"Life Exp"]
# end inclusive

# Select by row,column index – do not use this anymore
states.ix[0:2,1:3] # end exclusive?
states.ix[0:4,"Population":"Life Exp"]

<div style="font-size:18px">Adding/Deleting</div> 

We can add columns by selecting a new column, then assigning a value​

Note we cannot use the column attribute to create a new column​

Use the **del** keyword to delete a column​

In [ ]:
# Add Column
states["NewCol"] = 4
states.head()
 
# Delete Column
del states["NewCol"]
states.head()

We can delete rows with **.drop**​

Columns as well.​

We can add rows with **.append** ​

Columns as well.​

In [ ]:
# Delete Row/Add Row
states.drop(states.index[0])
states.drop(states.index[-1])
states1 = states[0:10]
states2 = states[10:25]
states3 = states[25:]
states1.append([states2,states3])

<div style="font-size:18px">Reindexing After Subsetting</div> 

We often take a subset of a dataframe, and we may need to reindex the rows afterwards. ​

This is not done automatically post subset.​

In [ ]:
# Reindex
states.sub = states[states.Population < 1000]
states.sub = states.sub.reset_index()
del states.sub["index"]
states.sub 

# Alternatively
states.sub = states.sub.reset_index(drop=True)

<div style="font-size:18px">Missing Values</div> 

Pandas uses NaN to cover missing values​

You can drop missing data axis (rows or cols) with **.dropna()**

You can fill missing values in with **fill.na()**

There is a built in method for forward fill or back fill​

In [ ]:
# Missing Data
states_miss  = states.copy()
# Set all Population values below 1000 to missing
states_miss["Population"][states["Population"] < 1000] = np.NaN
states_miss.Population[states.Population < 1000] = np.NaN
# drop missing data
states_miss.dropna()
states_miss.fillna(0)
states_miss.fillna(method="ffill")

We use **.isnull()** and **.notnull()** to check for missing values (boolean result)​

In [ ]:
# isnull
states_miss.isnull()
states_miss.notnull()

# How would we check which rows are null?

<div style="font-size:18px">Functions on DF</div> 

Lets think of functions in terms of number of inputs relative to number of outputs​

Functions which return one output for each input operate elementwise​

Functions which reduce a list of inputs to 1 output operate column-wise (by defult)​

In [ ]:
# Functions on DataFrames
states.mean()
#Whats the Difference between these two?
states.mean()["Population"]
states["Population"].mean()
 
# Returning More than One Value
states_cop = states.copy()
res = states_cop.ix[:,"Population" : "Illiteracy"].diff()
pd.concat([states_cop.ix[:,"State"],res],axis=1)

Vectorization in Pandas can handle a wide variety of situations​

You can apply functions to Pandas objects in three ways:​

  - Table-wise using **pipe()**

  - Row or column-wise using **apply()**

  - Element-wise using **applymap()**
  
Use table-wise functions to operate on an entire dataframe​

In the sample below, we add a number to each element in the table (in this case, 2)

In [ ]:
import pandas as pd
import numpy as np

def adder(ele1,ele2):
    return ele1+ele2

df = pd.DataFrame(np.random.randn(5,3),columns=['col1','col2','col3'])
df.pipe(adder,2)
print(df.apply(np.mean))

By row-wise or column-wise, what we mean is applying a function along a particular axis​

Which means we can use this in higher-order matrices too​

Each axis has an index. List the index to set the application​

Columns is index 0 and default​

Rows is index 1​

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(5,3),columns=['col1','col2','col3'])
df.apply(np.mean)
print(df.apply(np.mean))

Doing an element-wise operation is the same as our original notion of vectorization​

Note in the sample here we are combining a table-wise and element-wise operation as a comparison​

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(5,3),columns=['col1','col2','col3'])
print(df.apply(np.mean))    # old mean
print(df.applymap(lambda x:x*100)) # modify elements
print(df.applymap(lambda x:x*100).apply(np.mean)) # new mean

<div style="font-size:18px">Sorting a DF</div> 

We use **.sort_values()** to sort a data frame​

We can sort by either the index or a column(s)​

In [ ]:
# Sorting
states.sort_values("Population")
states.sort_values("Population“, ascending=True)

# Multiple sorts
states.sort_values(by=["Illiteracy","Population"]) states.sort_values(by=["Illiteracy","Population"],
ascending=[True,False])

Iterating over a series (1d) object is similar to an array or tuple​

Iterating over a dataframe or panel is a little trickier​

The iteration for them provides a dictionary object which has the columns/values of rows/values​

  - Use iteritems() for column-wise​

  - Use iterrows() for row-wise​

  - User itertuples() to convert rows to tuples​
  
The **iteritems()** method produces key, value pairs with the column name and the column values as a series​

In [ ]:
import pandas as pd
import numpy as np
 
df = pd.DataFrame(np.random.randn(4,3),columns=['col1','col2','col3'])
for key,value in df.iteritems():
    print(key,value)

The **iterrows()** method returns a dictionary with each key, value pair as a row index and a series of row values​

Each value is associated with its specific column label​

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(4,3),columns = ['col1','col2','col3'])
for row_index,row in df.iterrows():
    print(row_index, row)

<div style="font-size:18px">Unique Values</div>

We can use the .unique() function of Series to Get unique values from a column​

Use the sorted function to sort the output from unique

In [ ]:
# Unique Values
states["Illiteracy"].unique()

# Unique Values from data set
states.drop_duplicates()

<div style="font-size:18px">Merge</div> 

We can use the **pd.merge()** function

In [ ]:
# Import Dataframe
states = pd.read_csv(r"C:\data\states.csv")
states2 = pd.read_csv(r"C:\data\states_extra.csv")

# Merge these together
pd.merge(states,states2,how="left", left_on="State",right_on=“ST")

<div style="font-size:18px">Reshaping</div> 

We often want to “reshape” a matrix​

A specific example would be “pivoting” (pivot tables anyone?)​

Another often used reshape is going from “long” to “wide”, and vice versa. ​

Finally, we may wish to transpose a dataframe or matrix​

There are other more complex reshaping use cases, but we will only briefly cover them​

We can “Stack” and “unstack” data frames​

In [ ]:
# reshaping a dataframe
state_sub = states.ix[0:3,1:3].copy()
state_sub.index = states.State[0:4]
state_sub.stack()
state_sub.stack().unstack()

# Can specify which dimension to unstack
state_sub.stack().unstack(0)
state_sub.stack().unstack(1)

<div style="font-size:18px">From Long to Wide</div> 

We have data indexed by a repeated variable (id) and another variable (time), with other values

In [ ]:
# Long to Wide
df = pd.DataFrame({"id": 	("a","a","b","b","c","c"),                   	"time": (1,2,1,2,1,2),
	"meas":range(6)})
wide = df.pivot("id","time","meas")

<div style="font-size:18px">From Wide to Long</div> 

We may wish to go back from Wide to Long

In [ ]:
# Wide to Long
wide["id"] = wide.index


pd.melt(wide,id_vars=["id"],
        value_vars=[1,2],var_name="Time",value_name="meas")

<div style="font-size:18px">Removing Duplicates</div> 

We can remove duplicates from a dataframe ​

**.duplicated()**

**.duplicates()**

In [ ]:
# Duplicates
df_dup  = df.append(df.iloc[1])

df_dup.duplicated()

df_dup.drop_duplicates()

<div style="font-size:18px">Binning</div> 

We want to discretize some data. ​

We have continuous data, we want groups…​

We can use **dataframe.cut()**

In [ ]:
# binning with cut
states.Population.describe()
bins = [0,1000,3000,5000,25000]
pd.cut(states.Population, bins)

# With Labels
states['Population_cat']= pd.cut(states.Population, bins, 
                                 labels=["small","med","large","huge"])

<div style="font-size:18px">Working with Text</div> 

Strings in Pandas are roughly the same as strings in Python​

We simply operate on series rather than a single object​

Pandas provides many of the same methods, such as **len()**, **lower()**, **upper()**, **split()** and others you have seen before​

Pandas methods also usually ignore missing NaN values​

In [ ]:
s = pd.Series(['Tom', 'William Rick', 'John', 'Alber@t'
               , np.nan, '1234','SteveSmith'])

print(s)
print(s.str.lower())
print(s.str.upper())
print(s.str.len())

We often want to apply functions to groups within our dataset. ​

  - What is the mean value within group?​

  - What is the variance within group?​

  - Perform a linear regression within group, then get the slope estimates out.​

This has been conceptualized as:​

  - Split​

  - Apply​

  - Combine​
  
<div style="font-size:18px">Group-wise Operation</div>

The first step is to establish the groups (SPLIT)​

In Pandas, we can use the **.groupby()** method for this​

Use states, and group on the variable we just created ​

In [ ]:
# Group By
grp = states.groupby("Population_cat")
grp.mean()
grp.var()
 
# Only One variable
states.Income.groupby(states.Population_cat).mean()

We can index the group-by with a dynamically created value

In [ ]:
# Group By Dynamic Variables
states.Illiteracy.groupby(states.Income < 4100).mean()

We can iterate through the groups, allowing more flexibility to do things

In [ ]:
# Group By Iteration
# we need to convert the series 
# to a bunch of # strings so we can grab the first letter
states['firstlet']= states.State.astype(str).str[0]
grp = states.groupby("firstlet")
for (name,data) in grp:
    print(name)
    print(data)

<div style="font-size:18px">Aggregation</div> 

Use **grp.agg()** to pass in user written function​

**groupedobj.agg(function)**​

You can also pass in a list of length two tuples with names and functions to name the columns. ​

In [ ]:
# Aggregation
# Write your own function
def sterr(x):
    try:
        return np.std(x) / np.sqrt(len(x))
    except:
        return np.nan
sterr(states.Income)
grp = states.groupby(states.Income < 4100)["Illiteracy"]
grp.agg(sterr)
grp.agg([(“spread",sterr),
	   (“center",np.mean)])

<div style="font-size:18px">Use Vars instead of Index</div>

We can request the group by object returns variables (columns) instead of index or hierarchical indexes

In [ ]:
# Eliminate the index
grp = states.groupby(states.Income < 4100,as_index=False)
grp.mean()

<div style="font-size:18px">Joining Groupwise Aggregations</div> 

After calculating groups means, we may wish to rejoin them to the group. ​

Pandas calls this “transform”, where the transformed data is placed back in the context of the original data. ​

The result must be a scalar, or the appropriate sized array.

In [ ]:
# Transform 
grp = states.groupby(states.Income < 4100,as_index=False)["Illiteracy"]

grp.transform(np.mean)

<div style="font-size:18px">Cross Tabs</div>

Frequency Table

Classic statistical aggregation. How many observations occupy each group?

In [ ]:
# Cross Tabs 
pd.crosstab(states.Income < 4100,states. Population_cat) 
pd.crosstab(states.Income < 4100,states. Population_cat,margins=True)

<div style="font-size:18px">Applying Functions</div> 

How could we get the percentages rather than the frequencies?​

We can apply a function across rows or columns using **pd.apply()**

In [ ]:
# Create the table
tbl1 = pd.crosstab(states.Income < 4100,states.Population_cat)

# Applying Functions
tbl1.apply(lambda x: x/x.sum(),axis=0)
tbl1.apply(lambda x: x/x.sum(),axis=1)

Because we do a lot of data analytics with Pandas, it’s good to know some statistics​

  - Pandas supports all the basics​

  - Mean, median, mode, min, max​

  - Covariance, Correlation, Ranking

In [ ]:
s = pd.Series([1,2,3,4,5,4])
print(s.pct_change())
print(s.cov(s2))

df = pd.DataFrame(np.random.randn(5, 2))
print(df.pct_change())
print(df.mean())
print(df.median(axis=1))
print(df.mode(axis=1))

<div style="font-size:18px">Correlation</div> 

A quick note on correlation. Correlation shows the linear relationship between two series​

There are multiple ways to compute the correlation like pearson, spearman and kendall​

  * Pearson is the default​

Correlate a pair of rows or the entire dataframe​

In [ ]:
frame = pd.DataFrame(np.random.randn(10, 5), columns=['a', 'b', 'c', 
                                                      'd', 'e'])

print(frame['a'].corr(frame['b']))
print(frame.corr())

<div style="font-size:18px">Data Ranking</div> 

Sometimes we want to “rank” our rows in order to see how they compare with the rest of the data​

  - Best sales overall or by month or year​

  - Fastest completion times, best gas mileage, etc.​

Ties are handled according to a method parameter (average, min, max, first)​

  - The default is to average ties​

In [ ]:
s = pd.Series(np.random.np.random.randn(5), index=list('abcde'))
s['d'] = s['b'] # so there's a tie
print(s.rank())

<div style="font-size:18px">Windowing</div> 

What is “windowing?” Imagine you are a car salesman and you want to know if your sales trends are heading in the right direction​

  - Month over month sales might not give an accurate picture as sales can vary quite a bit from month to month​

  - What you need is a “window” of time to smooth out the monthly volatility so you can see if the sales for the window is increasing or decreasing​

Windows consist of several types​

  - Rolling (same size over time)​

  - Expanding (accumulates over time)​

  - Weighted (gives more importance to subsets of the data)​
  
Detailed use and explanation of these functions is beyond the scope of this course, but really it’s a matter of supplying parameters such as the size of the window, how many periods you want and the statistical measures you want to apply​

In [ ]:
df = pd.DataFrame(np.random.randn(10, 4),
   index = pd.date_range('1/1/2000', periods=10),
   columns = ['A', 'B', 'C', 'D'])
# rolling window of 3 periods
print(df.rolling(window=3).mean())
# expanding window, miniumum 3 periods
print(df.expanding(min_periods=3).mean())
# weighted average, with decay specified
print(df.ewm(com=0.5).mean())

<div style="font-size:18px">Visuals</div> 

We have a whole section on visuals, but because it is so important to data analytics, pandas provides visuals too​

  - Usually as a wrapper to matplotlib so this ties nicely into the next section​

Pandas supports many types of plots​

  - Line, bar, area, box, histogram and scatter plots among others

In [ ]:
df = pd.DataFrame(np.random.randn(10,4),
        index=pd.date_range('1/1/2000',
        periods=10), columns=list('ABCD'))

df.plot()

In [ ]:
df = pd.DataFrame(np.random.rand(10,4),
        columns=['a','b','c','d'])
df.plot.bar()

In [ ]:
# stacked bar
df.plot.bar(stacked=True)

In [ ]:
# horizontal stacked bar
df.plot.barh(stacked=True)

In [ ]:
df = pd.DataFrame({'a':np.random.randn(1000)+1
                   ,'b':np.random.randn(1000),'c':
np.random.randn(1000) - 1}, columns=['a', 'b', 'c'])
# histogram
df.plot.hist(bins=20)

In [ ]:
df = pd.DataFrame(np.random.rand(10, 5)
        , columns=['A', 'B', 'C', 'D', 'E'])
df.plot.box()

In [ ]:
df = pd.DataFrame(np.random.rand(50, 4)
    , columns=['a', 'b', 'c', 'd'])
df.plot.scatter(x='a', y='b')

In [ ]:
df = pd.DataFrame(3 * np.random.rand(4)
    , index=['a', 'b', 'c', 'd'], columns=['x'])
df.plot.pie(subplots=True)

# Test Your Knowledge

Create a function to:

> 1. Take an array as input (from a data frame)
> 2. Output the mean, median, and a sorted list of unique values